### PR TITLE
APRS SSID and user controlled reporting

### PR DESCRIPTION
**Pull request by oh7nfc**
This version of bm-rpt2aprs is modified for personal purposes. It still has new features which might be useful at server sites too.

1. The SSID is parsed from the hostpot DMR ID
2. The reporting can be controlled by tags in the desrcrpition field at BM Dashboard

### CODE REVIEW

**Comment by nonoo** [comment]
My main concern is that this can only be used for predefined repeater IDs (the removal of the dbus_get_repeater_ids_for_network() function). Please figure something out so the current method and your new features can work together.

**Comment by cyanide-burnout** [comment]
I fully agree with position of nonoo. Request cannot be merged when list of repeater is predefined.

**Comment by oh7nfc** [comment]
Yes, yes - you are right, my version of the aprs reporting is not intended for Brandmeister servers. It is a personal version with predefined hotspot ids and is run outside of any BM servers.

The reason for this pull request is that I would like to get next two functions to the original version:
1) The SSID of an APRS object is parsed from the id, ex. 244301801 forms an APRS object OH3NFC-01
2) An individual user can prevent APRS reporting by adding a keyword NOAPRS or NOGATE to the Priority Message on the Brandmeister dashboard.

You might do a partial merge and copy only the lines doing the ssid parsing and the reporting skipping, or should I do another fork of the original repository and put the suggested modificatios there?

Cheers de Veijo

**Comment by zarya** [comment]
Please resubmit the pullrequest for just the ssid parsing and reporting skipipng.

**Comment by oh7nfc** [comment]
Yes, I'll do that in the near future and resubmit a pull request only containing the new features.

**Pull request closed without merging**
