### PR TITLE
Fix hundredths convertion DD2DMS

### PR DESCRIPTION
**Pull request by pjao**
Fix of (https://github.com/BrandMeister/bm-rpt2aprs/issues/3)

Trying to do the request (https://github.com/BrandMeister/bm-rpt2aprs/pull/4#issuecomment-329792632)

### CODE REVIEW

**Comment by nonoo** [comment]
Please add a comment describing what's happening before the substr line.
Use $degrees['minutes']++ instead of $degrees['minutes'] = ++$degrees['minutes'];
If it does not work, use $degrees['minutes'] = $degrees['minutes'] + 1;

**Comment by pjao** [comment]
$degrees['minutes']++ i doesn't work so have to use $degrees['minutes'] = $degrees['minutes'] + 1;

**Comment by nonoo** [comment]
Please describe what the code does, and not what the code is what for in the comment

**Comment by pjao** [comment]
What about now?

**Pull request merged**
