### PR TITLE
support multiple server instances

### PR DESCRIPTION
**Pull request by stefansaraev**
first commit is a simple run.sh I use for cron. let me know if it's unwanted
second commit is just whitespaces cleanup. no functional changes

review with ?w=1 (https://github.com/BrandMeister/bm-rpt2aprs/pull/13/commits/df049764b4eef6d1effc7780bdbb6f0a40b78b53?w=1)

### CODE REVIEW

**Comment by nonoo** [comment]
Please keep tabs instead of modifying them to spaces.

**Comment by stefansaraev** [comment]
ok. removed seconnd commit.

**Comment by nonoo** [comment]
Please move stuff out of common.php into functions.
Please do not modify indentation of bm-rpt2aprs.php as it is unnecessary.
Also please use tabs instead of whitespaces where needed.

**Comment by stefansaraev** [comment]
well, forget it.

**Pull request closed without merging**
